GET {{url}}/test
Content-Type: application/json
#Authorization: Bearer {{token}}

###
GET {{url}}/posts
Authorization: Bearer {{token}}

###
GET {{url}}/posts/1
Authorization: Bearer {{token}}

###
POST {{url}}/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "header": "Technology Part 2",
  "content": "This is a technology blog for part 2"
}

###
PUT {{url}}/posts/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "header": "Technology Part 4",
  "content": "This is a technology blog for part 4"
}

###
DELETE {{url}}/posts/1
Authorization: Bearer {{token}}

###
DELETE {{url}}/posts/1
Authorization: Bearer {{token}}
