GET {{url}}/test
Content-Type: application/json
#Authorization: Bearer {{token}}

###
GET {{url}}/posts
Authorization: Bearer {{token}}

###
GET {{url}}/posts/1
Authorization: Bearer {{token}}

###
POST {{url}}/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "header": "Technology",
  "content": "This is a technology blog"
}

###
PUT {{url}}/posts/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "header": "Technology Test Update",
  "content": "This is a technology blog"
}

###
DELETE {{url}}/posts/1
Authorization: Bearer {{token}}
