name: API JAVALIN WORKFLOW
on:
  push:
    branches: [ main, part_01 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      -
        name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      -
         # copy jar file to the root directory on my server
        name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/app.jar
          remote: /deployment/app.jar
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}

