name: API JAVALIN WORKFLOW
on:
  push:
    branches: [ deployment_part_01 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
#      - name: Build with Maven cloud
#        run:   mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=tysker_3sem-deployment-backend -Dsonar.organization=tysker -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
#        env:
#          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      -
        # https://docs.docker.com/build/ci/github-actions/tr
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/javalin-auth-api:latest

