name: API JAVALIN WORKFLOW
on:
  push:
    branches: [ main, part_01 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      -
        name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Copy Jar to Server
        run: scp -o StrictHostKeyChecking=no -P 2375 target/app.jar root@${{ secrets.SERVER_IP }}:/deployment/app.jar
          - env:
              SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

